### ISSUE TITLE
unsafe redirect

### ISSUE THREAD

**Issue by msacks** [praized/marelle#5]
I plugged in my 4sq client ID into one of the examples and tried to load it in Chrome from localhost, but I get 

The webpage at file://localhost/Downloads/praized-marelle-f217980%202/examples/checkins/index.html#error=redirect_uri_mismatch might be temporarily down or it may have moved permanently to a new web address.
Error 311 (net::ERR_UNSAFE_REDIRECT): Unknown error.

**Comment by quickredfox** [comment]
You have to be behind a web server. file:// urls do not work with Ajax.
