### ISSUE TITLE
Can't search places, without requiring login

### ISSUE THREAD

**Issue by OmarIthawi** [praized/marelle#6]
I realize that this is mostly a Foursquare API limitation. But I would like to state it here anyway in case that there is a way around that. This is my related stackoverflow question:  http://stackoverflow.com/q/8694492/161278 . The main reason that I'm stating this that the other similiar APIs like Google Places API provides such convenient way through browser without a visible authentication to the user.

**Comment by quickredfox** [comment]
Got your reply on stackoverflow ;)
